---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Williams-K.
--- DateTime: 20/12/2022 20:06
---
function test()
    local player = getSpecificPlayer(0)
    player:Say('yolo1')
end

--Events.OnOjectLeftMouseButtonUp.Add(test)
Events.OnTick.Add(test)
