---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Williams-K.
--- DateTime: 21/12/2022 12:25
---
IngeniousProceduralDistributions = {};

IngeniousProceduralDistributions.list =  {

    IngeniousLibraryBooks = {
        rolls = 4,
        items = {
            "MaintenanceOfCombatEquipment1", 8,
        },
        junk = {
            rolls = 1,
            items = {

            }
        }
    }
}